name = "HB Starter Theme Template"
license = "MIT"
licenselink = "https://pic.g0f.cn/"
description = "keep simple, keep stupid"
homepage = "https://pic.g0f.cn/"
demosite = "https://pic.g0f.cn/"
tags = [
    "archive",
    "blog",
    "posts",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "naive"
homepage = "hhttps://pic.g0f.cn/"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]