name = "HB Starter Theme Template"
license = "MIT"
licenselink = "https://github.com/jobcher"
description = "keep simple, keep stupid"
homepage = "https://github.com/jobcher"
demosite = "https://test.jobcher.com/"
tags = [
    "archive",
    "blog",
    "posts",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "jobcher"
homepage = "https://test.jobcher.com/"
