name: github_trend

on:
  schedule:
    # 每天，执行一次
    - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  github_trend:
    runs-on: ubuntu-latest
    env:
      BAIDU_TRANSLATE_API_KEY: ${{ secrets.BAIDU_TRANSLATE_API_KEY }}
      BAIDU_TRANSLATE_API_ID: ${{ secrets.BAIDU_TRANSLATE_API_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1

      - name: Prepare and push changes
        run: |
          cd ./public

          # 配置 Git 用户信息
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 初始化 Git 仓库
          git init

          # 添加所有更改
          git add -A

          # 提交更改
          git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By GitHub Actions"

          # 复制文件到目标路径 content/posts/zx
          cp your_file_path /content/posts/zx

          # 添加新文件到 Git
          git add .

          # 提交更改
          git commit -m "Add new content to content/posts/zx"

          # 配置远程仓库地址
          git remote add origin "https://g0fcn:${{ secrets.GH_TOKEN }}@github.com/g0fcn/hugo-blog.git"

          # 推送更改到远程仓库的 main 分支
          git push --force --quiet origin main:main
