name: Hugo Module Setup

on:
  push:
    branches:
      - main

jobs:
  setup-modules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Initialize Hugo Modules
      run: hugo mod init github.com/g0fcn/new-blog.git
