name: GitHub Pages

on:
  # auto deploy when pushing to specified branches.
  push:
    branches:
      - main

  # allow deploying manually.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --enableGitInfo    

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy Web	
        uses: peaceiris/actions-gh-pages@v3.8.0	
        with:	
            PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}	
            EXTERNAL_REPOSITORY: jobcher/test.github.io	
            PUBLISH_BRANCH: main	
            PUBLISH_DIR: ./public	
            commit_message: ${{ github.event.head_commit.message }}
